# Try container-based infrastucture
sudo: false

notifications:
  email: false

language: python


matrix:
  include:
    - python: 3.6
      os: linux
      dist: trusty
    - python: 3.5
      os: linux
      dist: trusty
    - python: 3.4
      os: linux
      dist: trusty
    - env: CC=gcc PYTHON_VERSION='3.7'
      language: generic
      os: osx

before_install:
  - ./.travis_before_install.sh

install:
  - ./.travis_install.sh
 
script:
  - ./.travis_test.sh

after_success:
  - ./.travis_deploy.sh
